### ISSUE TITLE
Heroic source jar not recognized as matching classes

### ISSUE THREAD

**Issue by mslinn** [softprops/heroic#2]
I created an Eclipse project from the heroic GitHub project using sbteclipse 11.2, using Windows XP SP3.

~/.sbt/plugins/build.sbt:
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse" % "latest.milestone")

Project available from:
https://github.com/softprops/heroic

Generated Eclipse project with:
sbt "eclipse with-source=true"

In herioc.scala, pressing F3 on the import sbt.Project does not display the source, instead the message "Current text selection cannot be opened in an editor" appears. I could see the class file in the Eclipse editor, so I clicked on the "Change attached source" button and manually selected the matching source jar. This message appeared: "The source attachment does not contain the source for the file Project.class". I opened the source jar, and found that the class was in fact defined there.

Somehow Eclipse cannot recognize that the source matches the binary jar. Perhaps this is a bug in how Heroic is packaged. Somehow the wrong source jar has been associated with the binary jar.

I originally posted to [Scala IDE](http://www.assembla.com/spaces/scala-ide/support/tickets/1000844-sbt-source-jar-not-recognized-as-matching-classes#last_comment) and they suggested that this issue might be best followed up here.

**Comment by mslinn** [comment]
Comparing the contents of main_2.9.1-0.11.2.jar to main_2.9.1-0.11.2-sources.jar, I saw that there was no source for TaskKey.scala, Tags.scala, SettingGraph.scala, and others.

**Comment by softprops** [comment]
This sounds more like a bug with your editor. These are the sources in heroic https://github.com/softprops/heroic/tree/master/src/main/scala. I'm not sure what TaskKey, Tags, SettingsGraph.scala are? I don't normally package projects to cater to a specific IDE, I code using a text editor and leave compilation and other tasks to sbt. If I can do `sbt compile` without error, it sounds like a bug with the IDE or that the IDE requires proprietary package formatting.

**Comment by mslinn** [comment]
I don't think Scala IDE is at fault. I opened the jars in 7-zip and manually matched up the .scala files against the .class files and found discrepancies. Either sbteclipse is not finding matching src/binary jars, or the Heroic jars are deployed incorrectly on the public repository.

**Comment by mslinn** [comment]
BTW, notice I used "latest.milestone", not a specific Heroic milestone. Not many people know about this [Ivy option](http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html), "latest.integration" is more widely documented.

**Comment by softprops** [comment]
Heroic is not yet published which could be the problem if your IDE is looking for published artifacts

**Comment by mslinn** [comment]
main_2.9.1-0.11.2.jar is an SBT jar, not a Heroic jar. I opened a ticket with sbteclipse; maybe I should also open a ticket with xsbt.

**Comment by mslinn** [comment]
I just used gen-idea to generate an IntelliJ IDEA project from Heroic, and the SBT jars resolved fine; in IDEA I can click on an sbt.Project reference and go to the source code for sbt.Project. Problem must relate to Scala IDE or sbteclipse.
